# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-gff3}
  s.version = "0.8.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pjotr Prins"]
  s.date = %q{2011-01-03}
  s.default_executable = %q{gff3-fetch}
  s.description = %q{GFF3 (genome browser) information and digest mRNA and CDS sequences.
Options for low memory use and caching of records.
Support for external FASTA files.
}
  s.email = %q{pjotr.prins@thebird.nl}
  s.executables = ["gff3-fetch"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gff3-fetch",
    "bio-gff3.gemspec",
    "lib/bio-gff3.rb",
    "lib/bio/db/gff/gffassemble.rb",
    "lib/bio/db/gff/gffdb.rb",
    "lib/bio/db/gff/gfffasta.rb",
    "lib/bio/db/gff/gfffileiterator.rb",
    "lib/bio/db/gff/gffinmemory.rb",
    "lib/bio/db/gff/gffnocache.rb",
    "lib/bio/db/gff/gffparser.rb",
    "lib/bio/output/gfffastawriter.rb",
    "lib/bio/system/lruhash.rb",
    "spec/gff3_assemble2_spec.rb",
    "spec/gff3_assemble3_spec.rb",
    "spec/gff3_assemble_spec.rb",
    "spec/gff3_fileiterator_spec.rb",
    "spec/gffdb_spec.rb",
    "test/data/gff/MhA1_Contig1133.fa",
    "test/data/gff/MhA1_Contig1133.gff3",
    "test/data/gff/MhA1_Contig125.fa",
    "test/data/gff/MhA1_Contig125.gff3",
    "test/data/gff/standard.gff3",
    "test/data/gff/test-cds.gff3",
    "test/data/gff/test-ext-fasta.fa",
    "test/data/gff/test-ext-fasta.gff3",
    "test/data/gff/test.gff3",
    "test/helper.rb",
    "test/test_bio-gff3.rb"
  ]
  s.homepage = %q{http://github.com/pjotrp/bioruby-gff3}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{BioRuby GFF3 plugin for big data}
  s.test_files = [
    "spec/gff3_assemble2_spec.rb",
    "spec/gff3_assemble3_spec.rb",
    "spec/gff3_assemble_spec.rb",
    "spec/gff3_fileiterator_spec.rb",
    "spec/gffdb_spec.rb",
    "test/helper.rb",
    "test/test_bio-gff3.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.3.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.3.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<bio>, [">= 1.3.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.3.1"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.3.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.3.1"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

